#  Copyright © Microsoft Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

apiVersion: v1
kind: Service
metadata:
  name: legal
  namespace: osdu
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: legal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: legal
  namespace: osdu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legal
  template:
    metadata:
      labels:
        app: legal
        aadpodidbinding: osdu-identity
    spec:
      containers:
      - name: legal
        image: community.opengroup.org:5555/osdu/platform/security-and-compliance/legal/legal-master
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /api/legal/v1/swagger-ui.html
            port: 80
        volumeMounts:
        - name: azure-keyvault
          mountPath: "/mnt/azure-keyvault"
          readOnly: true
        env:
        - name: spring_application_name
          value: legal
        - name: server.servlet.contextPath
          value: /api/legal/v1/
        - name: server_port
          value: "80"
        - name: ACCEPT_HTTP  # TEMPORARY UNTIL HTTPS
          value: "true"
        - name: KEYVAULT_URI
          valueFrom:
            configMapKeyRef:
              name: osdu-svc-properties
              key: ENV_KEYVAULT
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: clientid
              key: clientid
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: clientpassword
              key: clientpassword
        - name: AZURE_TENANT_ID
          valueFrom:
            configMapKeyRef:
              name: osdu-svc-properties
              key: ENV_TENANT_ID
        - name: aad_client_id
          valueFrom:
            secretKeyRef:
              name: appid
              key: appid
        - name: appinsights_key
          valueFrom:
            secretKeyRef:
              name: appinsights
              key: appinsights
        - name: servicebus_namespace_name
          valueFrom:
            configMapKeyRef:
              name: osdu-svc-properties
              key: ENV_SERVICEBUS_NAMESPACE
        - name: storage_account
          valueFrom:
            configMapKeyRef:
              name: osdu-svc-properties
              key: ENV_STORAGE_ACCOUNT
        - name: azure_activedirectory_session_stateless
          value: "true"
        - name: azure_activedirectory_AppIdUri
          value: "api://$(aad_client_id)"
        - name: cosmosdb_database
          value: osdu-db
        - name: LOG_PREFIX
          value: legal
        - name: azure_storage_container_name
          value: legal-service-azure-configuration
        - name: azure_storage_enable_https
          value: "true"
        - name: legal_service_region
          value: us
        - name: servicebus_topic_name
          value: legaltags
        - name: entitlements_service_endpoint
          value: http://entitlements-azure/entitlements/v1
        - name: entitlements_service_api_key
          value: "OBSOLETE"
      volumes:
      - name: azure-keyvault
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: azure-keyvault
