#  Copyright © Microsoft Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Required Group Variables - `Infrastructure Pipeline Variables`
  # AGENT_POOL
  # BUILD_ARTIFACT_NAME
  # SERVICE_CONNECTION_NAME
  # TF_VAR_remote_state_account
  # TF_VAR_remote_state_container

# Required Group Variables - `Infrastructure Pipeline - {env_name}`
  # TF_VAR_aks_agent_vm_count
  # ARM_SUBSCRIPTION_ID
  # TF_VAR_aks_agent_vm_count
  # TF_VAR_cosmosdb_replica_location
  # TF_VAR_data_sources_workspace_name
  # TF_VAR_flux_recreate
  # TF_VAR_gitops_path
  # TF_VAR_gitops_ssh_url
  # TF_VAR_gitops_url_branch
  # TF_VAR_image_repository_workspace_name
  # TF_VAR_resource_group_location

# Required Env Group Variables - `Infrastructure Pipeline Secrets - {env_name}` (for each {env_name})
  # elastic-username-ado-{env_name}
  # elastic-password-ado-{env_name}
  # elastic-endpoint-ado-{env_name}

# Deploy and validate infra changes once changes have been merged into
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - /infra/templates/osdu-r2-resources/*
    exclude:
    - /**/*.md

pr:
  autoCancel: true
  branches:
    include:
    - '*'
  paths:
    include:
    - /infra/templates/osdu-r2-resources/*
    exclude:
    - /**/*.md

variables:
- name: 'TF_VERSION'
  value: '0.12.29'
- name: 'GO_VERSION'
  value: '1.12.14'
- name: 'TF_ROOT_DIR'
  value: 'infra'
- name: 'PIPELINE_ROOT_DIR'
  value: 'devops/infrastructure'
- name: 'TEST_HARNESS_DIR'
  value: 'test-harness'
- group: 'Infrastructure Pipeline Variables'

stages:
- template: prepare-stage.yml
  parameters:
    environments:
    - name: 'test'
      enablePrIsolation: false
      resourceNameIsolationLevel: 8
    - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      - name: 'int'
        enablePrIsolation: false
        resourceNameIsolationLevel: 8

    configurations:
    - jobName: osdu_r2
      terraformWorkspacePrefix: ADO
      terraformTemplatePath: infra/templates/osdu-r2-resources
      deploymentTimeoutInMinutes: 120  # Not supported as a Variable :-(

