apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: osdu-ingress
  namespace: osdu
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/acme-challenge-type: http01
spec:
  tls:
  - hosts:
    - {{ .Values.global.ingress.hostname }}
    secretName: osdu-certificate
  rules:
    - host: {{ .Values.global.ingress.hostname }}
      http:
        paths:
          - backend:
              serviceName: default-service
              servicePort: 80
            path: /*
          - backend:
              serviceName: {{ .Release.Name }}-entitlements-azure
              servicePort: 80
            path: /entitlements/v1/*
          - backend:
              serviceName: {{ .Release.Name }}-legal
              servicePort: 80
            path: /api/legal/v1/*
          - backend:
              serviceName: {{ .Release.Name }}-storage
              servicePort: 80
            path: /api/storage/v2/*
          - backend:
              serviceName: {{ .Release.Name }}-indexer-service
              servicePort: 80
            path: /api/indexer/v2/*
          - backend:
              serviceName: {{ .Release.Name }}-search-service
              servicePort: 80
            path: /api/search/v2/*
