#  Copyright © Microsoft Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-keyvault
  namespace: osdu
spec:
  provider: azure
  secretObjects:
  - secretName: appinsights
    type: Opaque
    data:
    - objectName: "appinsights-key"
      key: appinsights
  - secretName: cosmos
    type: Opaque
    data:
    - objectName: "cosmos-primary-key"
      key: cosmos
  - secretName: storage
    type: Opaque
    data:
    - objectName: "storage-account-key"
      key: storage
  - secretName: diagnostics
    type: Opaque
    data:
    - objectName: "diagnostics-account-key"
      key: diagnostics
  - secretName: servicebus
    type: Opaque
    data:
    - objectName: "sb-connection"
      key: servicebus
  - secretName: tenant
    type: Opaque
    data:
    - objectName: "app-dev-sp-tenant-id"
      key: tenant
  - secretName: clientid
    type: Opaque
    data:
    - objectName: "app-dev-sp-username"
      key: clientid
  - secretName: clientpassword
    type: Opaque
    data:
    - objectName: "app-dev-sp-password"
      key: clientpassword
  - secretName: appid
    type: Opaque
    data:
    - objectName: "aad-client-id"
      key: appid
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    resourceGroup: "{{ .Values.global.azure.resourcegroup }}"
    keyvaultName: "{{ .Values.global.azure.keyvault }}"
    subscriptionId: "{{ .Values.global.azure.subscription }}"
    tenantId: "{{ .Values.global.azure.tenant }}"
    objects: |
      array:
        - |
          objectName: appinsights-key
          objectType: secret
        - |
          objectName: cosmos-primary-key
          objectType: secret
        - |
          objectName: storage-account-key
          objectType: secret
        - |
          objectName: diagnostics-account-key
          objectType: secret
        - |
          objectName: sb-connection
          objectType: secret
        - |
          objectName: app-dev-sp-tenant-id
          objectType: secret
        - |
          objectName: app-dev-sp-username
          objectType: secret
        - |
          objectName: app-dev-sp-password
          objectType: secret
        - |
          objectName: aad-client-id
          objectType: secret
