#  Copyright © Microsoft Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: osdu-identity
  namespace: osdu
spec:
  type: 0
  resourceID: "/subscriptions/{{ .Values.global.azure.subscription }}/resourcegroups/{{ .Values.global.azure.resourcegroup }}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{{ .Values.global.azure.identity }}"
  clientID: "{{ .Values.global.azure.identity_id }}"
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: osdu-identity-binding
  namespace: osdu
spec:
  azureIdentity: osdu-identity
  selector: osdu-identity