#  Copyright © Microsoft Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

#####################
# README: Defines an common set of supportive deploy stages that any external app service pipeline can call into.
#####################

parameters:
  providers: []
  serviceName: ''
  testCoreMavenPomFile: ''
  testCoreMavenOptions: ''
  testCoreMavenGoal: 'install'

stages:

- ${{ each provider in parameters.providers }}:
  - ${{ each environment in provider.environments }}:
    - stage: 'Deploy_${{ provider.name }}_${{ environment }}'

      variables:
      - group: 'Azure - Common'
      - group: 'Azure Common Secrets'
      - group: '${{ provider.name }} Target Env - ${{ environment }}'
      - group: '${{ provider.name }} Target Env Secrets - ${{ environment }}'
      - group: '${{ provider.name }} Service Release - ${{ parameters.serviceName }}'

      - name: artifactName
        value: 'drop'

      jobs:
      - deployment: Deploy
        pool:
          name: $(AGENT_POOL)
          demands: 
            - maven
        environment: ${{ environment }}
        strategy:
          runOnce:
            deploy:
              steps:
              - download: none

              - task: DownloadBuildArtifacts@0
                displayName: 'Pull Build Artifacts'
                inputs:
                  artifactName: '${{ variables.artifactName }}'
                  downloadPath: '$(System.DefaultWorkingDirectory)'

              - template: tasks/app-service-deployment-steps.yml
                parameters:
                  serviceName: ${{ parameters.serviceName }}
                  providerName: ${{ provider.name }}
                  testCoreMavenPomFile: ${{ parameters.testCoreMavenPomFile }}
                  testCoreMavenGoal: ${{ parameters.testCoreMavenGoal }}
                  testCoreMavenOptions: ${{ parameters.testCoreMavenOptions }}
                  artifactName: ${{ variables.artifactName }}
                  elasticEndpoint: $(elastic-endpoint)
                  environment: ${{ environment }}
