inputSpec: swagger.yaml
outputDir: out/java
generatorName: java
artifactId: org-platform-api
groupId: io.github.nur858
additionalProperties:
  apiPackage: org.platform.client.api
  invokerPackage: org.platform.client
  groupId: org.platform
