inputSpec: openapi.yaml
outputDir: out/java
templateDirectory: java/templates
generatorName: java

artifactId: com-microsoft-osdu-api
artifactVersion:  0.0.2
groupId: io.github.nur858
apiPackage: com.microsoft.osdu.client.api
invokerPackage: com.microsoft.osdu.client.invoker
modelPackage: com.microsoft.osdu.client.model

library: native
additionalProperties:
  useOptional: true
  serializableModel: false
  java8: true
  scmConnection: scm:git:git@github.com:Azure/osdu-infrastructure.git
  scmDeveloperConnection: scm:git:git@github.com:Azure/osdu-infrastructure.git
  scmUrl: https://github.com/Azure/osdu-infrastructure
  developerName: Azure
  developerEmail: opensource@microsoft.com
  developerOrganization: Microsoft
  developerOrganizationUrl: https://docs.microsoft.com/en-us/azure/
  licenseName: MIT License
  licenseUrl: http://www.opensource.org/licenses/mit-license.php

files:
  pom.mustache:
    templateType: API
    destinationFilename: pom.xml
