name: 'SDK Generate'

on:
  workflow_dispatch:

jobs:
  generator:
    runs-on: ubuntu-latest
    name: OpenAPI Code Generator
    steps:

      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Nodejs Client Library w/ the OpenAPITools Generator
        uses: openapi-generators/openapitools-generator-action@v1.3.0
        with:
          generator: javascript
          config-file: configs/node.yaml
          openapi-file: openapi.yaml

      - name: Generate Java Client Library w/ the OpenAPITools Generator
        uses: openapi-generators/openapitools-generator-action@v1.3.0
        with:
          generator: java
          config-file: configs/java.yaml
          openapi-file: openapi.yaml

      - name: Generate DotNet Core Client Library w/ the OpenAPITools Generator
        uses: openapi-generators/openapitools-generator-action@v1.3.0
        with:
          generator: csharp-netcore
          config-file: configs/dotnet-core.yaml
          openapi-file: openapi.yaml

      - name: Generate Nodejs Client Library w/ the OpenAPITools Generator
        uses: openapi-generators/openapitools-generator-action@v1.3.0
        with:
          generator: python-legacy
          config-file: configs/python.yaml
          openapi-file: openapi.yaml
      - name: Create Archive
        run: |
          tar -czvf csharp-netcore.tar.gz csharp-netcore-client
          tar -czvf java.tar.gz java-client
          tar -czvf nodejs.tar.gz javascript-client
          tar -czvf python.tar.gz python-legacy-client

      - name: Upload Code
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
      - uses: azure/CLI@v1
        run: |
          STORAGE_ACCOUNT= ${{secrets.STORAGE_ACCOUNT}}
          RESOURCE_GROUP=${{secrets.RESOURCE_GROUP}}
          STORAGE_KEY=$(az storage account keys list --account-name $STORAGE_ACCOUNT --resource-group $RESOURCE_GROUP --query '[0].value' --output tsv)

          # az storage blob upload \
          #   --account-name $STORAGE_ACCOUNT \
          #   --account-key  $STORAGE_KEY \
          #   --file csharp-netcore.tar.gz \
          #   --container-name files \
          #   --name csharp-netcore.tar.gz

          # az storage blob upload \
          #   --account-name $STORAGE_ACCOUNT \
          #   --account-key  $STORAGE_KEY \
          #   --file java.tar.gz \
          #   --container-name files \
          #   --name java.tar.gz

          # az storage blob upload \
          #   --account-name $STORAGE_ACCOUNT \
          #   --account-key  $STORAGE_KEY \
          #   --file nodejs.tar.gz \
          #   --container-name files \
          #   --name nodejs.tar.gz

          # az storage blob upload \
          #   --account-name $STORAGE_ACCOUNT \
          #   --account-key  $STORAGE_KEY \
          #   --file python.tar.gz \
          #   --container-name files \
          #   --name python.tar.gz
          # az storage blob upload \
          #   --account-name $STORAGE_ACCOUNT \
          #   --account-key  $STORAGE_KEY \
          #   --file openapi.yaml \
          #   --container-name files \
          #   --name swagger.yaml

      - name: Publish Maven Artifacts
        run: |
          ls -al

