name: 'SDK Generate'

on:
  workflow_dispatch:

jobs:
  generator:
    runs-on: ubuntu-latest
    name: OpenAPI Code Generator
    steps:

      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Nodejs Client Library w/ the OpenAPITools Generator
        uses: openapi-generators/openapitools-generator-action@v1.3.0
        with:
          generator: javascript
          config-file: configs/node.yaml
          openapi-file: openapi.yaml

      - name: Generate Java Client Library w/ the OpenAPITools Generator
        uses: openapi-generators/openapitools-generator-action@v1.3.0
        with:
          generator: java
          config-file: configs/java.yaml
          openapi-file: openapi.yaml

      - name: Generate DotNet Core Client Library w/ the OpenAPITools Generator
        uses: openapi-generators/openapitools-generator-action@v1.3.0
        with:
          generator: csharp-netcore
          config-file: configs/dotnet-core.yaml
          openapi-file: openapi.yaml

      - name: Generate Nodejs Client Library w/ the OpenAPITools Generator
        uses: openapi-generators/openapitools-generator-action@v1.3.0
        with:
          generator: python-legacy
          config-file: configs/python.yaml
          openapi-file: openapi.yaml

      - name: Upload Code
        run: |
          ls -al

      - name: Publish Maven Artifacts
        run: |
          ls -al

