name: 'SDK Generate'

on:
  workflow_dispatch:

jobs:
  generator:
    runs-on: ubuntu-latest
    name: OpenAPI Code Generator
    steps:

      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Nodejs Client Library w/ the OpenAPITools Generator
        uses: openapi-generators/openapitools-generator-action@v1.3.0
        with:
          generator: javascript
          config-file: configs/node.yaml
          openapi-file: openapi.yaml

      - name: Generate Java Client Library w/ the OpenAPITools Generator
        uses: openapi-generators/openapitools-generator-action@v1.3.0
        with:
          generator: java
          config-file: configs/java.yaml
          openapi-file: openapi.yaml
          template-dir: java/templates
          command-args: -p java8=true

      - name: Generate DotNet Core Client Library w/ the OpenAPITools Generator
        uses: openapi-generators/openapitools-generator-action@v1.3.0
        with:
          generator: csharp-netcore
          config-file: configs/dotnet-core.yaml
          openapi-file: openapi.yaml

      - name: Generate Nodejs Client Library w/ the OpenAPITools Generator
        uses: openapi-generators/openapitools-generator-action@v1.3.0
        with:
          generator: python-legacy
          config-file: configs/python.yaml
          openapi-file: openapi.yaml
      - name: Create Archive
        run: |
          tar -czvf csharp-netcore.tar.gz csharp-netcore-client
          tar -czvf java.tar.gz java-client
          tar -czvf nodejs.tar.gz javascript-client
          tar -czvf python.tar.gz python-legacy-client

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 

      - name: Upload OpenAPI File
        uses: azure/CLI@v1
        with: 
          inlineScript: |
            az storage blob upload \
              --account-name ${{ secrets.STORAGE_ACCOUNT }} \
              --auth-mode  key \
              --file openapi.yaml \
              --container-name files \
              --name swagger.yaml

      - name: Upload DotNET Core SDK
        uses: azure/CLI@v1
        with: 
          inlineScript: |
            az storage blob upload \
              --account-name ${{ secrets.STORAGE_ACCOUNT }} \
              --auth-mode  key \
              --file csharp-netcore.tar.gz \
              --container-name files \
              --name csharp-netcore.tar.gz

      - name: Upload Java SDK
        uses: azure/CLI@v1
        with: 
          inlineScript: |
            az storage blob upload \
              --account-name ${{ secrets.STORAGE_ACCOUNT }} \
              --auth-mode  key \
              --file java.tar.gz \
              --container-name files \
              --name java.tar.gz

      - name: Upload NodeJS SDK
        uses: azure/CLI@v1
        with: 
          inlineScript: |
            az storage blob upload \
              --account-name ${{ secrets.STORAGE_ACCOUNT }} \
              --auth-mode  key \
              --file nodejs.tar.gz \
              --container-name files \
              --name nodejs.tar.gz

      - name: Upload Python SDK
        uses: azure/CLI@v1
        with: 
          inlineScript: |
            az storage blob upload \
              --account-name ${{ secrets.STORAGE_ACCOUNT }} \
              --auth-mode  key \
              --file python.tar.gz \
              --container-name files \
              --name python.tar.gz
              
      - name: Azure logout
        run: |
              az logout
        if: always()

