name: 'Maven Artifacts'

on:
  workflow_dispatch:

jobs:
  generator:
    runs-on: ubuntu-latest
    name: Publish Maven Artifacts
    steps:

      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish Maven Artifacts
        run: |
          ls -al

